### ISSUE TITLE
Media

### ISSUE THREAD

**Issue by cmcollander** [cmcollander/CompSciGUI#22]
We need 128x128 (or similar) images of the following, preferably PNG file with an Alpha layer
- Ship
- Dock
- Kraken
- Godzilla
- Leviathan
- Sea Serpent

We need mp3 files of the following
- Kraken Sound
- Godzilla Sound
- Leviathan Sound
- Sea Serpent Sound

**Comment by rafeykhan** [comment]
are we using the png's Dr Becker provided, or our own?

**Comment by cmcollander** [comment]
We aren't using Dr Becker's. The 2d map is actually drawn with rectangles and text on the fly. These pictures are for the update screens which ive found good pics for already. This issue is mainly still standing for the mp3s

**Comment by rafeykhan** [comment]
Great! I'll get on the mp3s as soon as i get home.
On Apr 8, 2015 4:12 PM, Chris Collander notifications@github.com wrote:We aren't using Dr Becker's. The 2d map is actually drawn with rectangles and text on the fly. These pictures are for the update screens which ive found good pics for already. This issue is mainly still standing for the mp3s
