### ISSUE TITLE
monster on collided ships

### ISSUE THREAD

**Issue by rafeykhan** [cmcollander/CompSciGUI#40]

**Comment by rafeykhan** [comment]
should remove both ships (correct??)

**Comment by cmcollander** [comment]
are you saying that if a monster goes over a spot that has more than one ship, then it should remove multiple ships from that spot? The only way more than one ship will be on a spot would be upon dragging a ship onto another, so yeah, we need to have it remove any ship that is at the location, rather than just the first one it finds.

i'm slightly unclear about your wording. The methods are there to determine if a monster collided with a ship, not if 2 ships collided together.

**Comment by rafeykhan** [comment]
sorry i didnt explain well. yeah thats what i meant.

**Comment by cmcollander** [comment]
fixed
